CREATE DATABASE TestSP;
GO

CREATE TABLE Persons
(
Id INT NOT NULL IDENTITY PRIMARY KEY,
FirstName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
SSN NVARCHAR(10) NOT NULL
);
GO

CREATE TABLE Accounts
(
Id INT NOT NULL IDENTITY PRIMARY KEY,
PersonId INT NOT NULL FOREIGN KEY REFERENCES Persons(Id),
Balance MONEY NOT NULL DEFAULT 0.00
);
GO