CREATE TABLE Users 
	(
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	Username NVARCHAR(50) UNIQUE NOT NULL,
	UserPassword NVARCHAR(100) NOT NULL CHECK(LEN(UserPassword) > 4),
	FullName NVARCHAR(200) NOT NULL,
	LastLoginTime DATETIME NOT NULL
	)