CREATE TABLE Users (
	Id INT IDENTITY,
	Username NVARCHAR(50) UNIQUE NOT NULL,
	UserPassword NVARCHAR(100) NOT NULL,
	FullName NVARCHAR(200) NOT NULL,
	LastLoginTime DATETIME DEFAULT GETDATE(),
	CHECK(UserPassword > 4),
	CONSTRAINT PK_Users PRIMARY KEY(Id))
GO
