-- MySQL Script generated by MySQL Workbench
-- 06/25/15 22:23:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema university
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema university
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `university` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `university` ;

-- -----------------------------------------------------
-- Table `university`.`faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`faculties` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`departments` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  `facultie_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_departments_faculties_idx` (`facultie_id` ASC)  COMMENT '',
  CONSTRAINT `fk_departments_faculties`
    FOREIGN KEY (`facultie_id`)
    REFERENCES `university`.`faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`professors` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  `department_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_professors_departments1_idx` (`department_id` ASC)  COMMENT '',
  CONSTRAINT `fk_professors_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `university`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  `department_id` INT NOT NULL COMMENT '',
  `professor_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_courses_departments1_idx` (`department_id` ASC)  COMMENT '',
  INDEX `fk_courses_professors1_idx` (`professor_id` ASC)  COMMENT '',
  CONSTRAINT `fk_courses_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `university`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_professors1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `university`.`professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  `cource_id` INT NOT NULL COMMENT '',
  `faculty_id` INT NOT NULL COMMENT '',
  `faculties_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_students_faculties1_idx` (`faculties_id` ASC)  COMMENT '',
  CONSTRAINT `fk_students_faculties1`
    FOREIGN KEY (`faculties_id`)
    REFERENCES `university`.`faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`cources_students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`cources_students` (
  `course_id` INT NOT NULL COMMENT '',
  `student_id` INT NOT NULL COMMENT '',
  INDEX `fk_cources_students_courses1_idx` (`course_id` ASC)  COMMENT '',
  INDEX `fk_cources_students_students1_idx` (`student_id` ASC)  COMMENT '',
  PRIMARY KEY (`course_id`, `student_id`)  COMMENT '',
  CONSTRAINT `fk_cources_students_courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `university`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cources_students_students1`
    FOREIGN KEY (`student_id`)
    REFERENCES `university`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`titles` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`professors_titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`professors_titles` (
  `professor_id` INT NOT NULL COMMENT '',
  `title_id` INT NOT NULL COMMENT '',
  INDEX `fk_professors_titles_professors1_idx` (`professor_id` ASC)  COMMENT '',
  INDEX `fk_professors_titles_titles1_idx` (`title_id` ASC)  COMMENT '',
  PRIMARY KEY (`professor_id`, `title_id`)  COMMENT '',
  CONSTRAINT `fk_professors_titles_professors1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `university`.`professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professors_titles_titles1`
    FOREIGN KEY (`title_id`)
    REFERENCES `university`.`titles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
