USE master
GO

CREATE DATABASE TestPerformance
GO

USE TestPerformance
GO

CREATE TABLE TestData
	(
		Id INT NOT NULL IDENTITY PRIMARY KEY,
		TestDate DATE NOT NULL,
		TestText NVARCHAR(50) NOT NULL
	)
GO

DECLARE @rows INT = 10000000

WHILE (@rows > 0)
	BEGIN
		DECLARE @testDate DATE = DATEADD(DAY, (ABS(CHECKSUM(NEWID())) % 5475), '2000-01-01')
		DECLARE @testText NVARCHAR = SUBSTRING(CONVERT(NVARCHAR(50), NEWID()),0,9)
		INSERT INTO TestData
		VALUES(@testDate, @testText)
		SET @rows = @rows - 1
	END

SELECT SUBSTRING(CONVERT(NVARCHAR(50), NEWID()),0,9)

SELECT DATEADD(DAY, (ABS(CHECKSUM(NEWID())) % 5475), '2000-01-01')
