USE master
GO

CREATE DATABASE TestPerformance
GO

USE TestPerformance
GO

CREATE TABLE TestData
	(
		Id INT NOT NULL IDENTITY PRIMARY KEY,
		TestDate DATE NOT NULL,
		TestText NVARCHAR(50) NOT NULL
	)
GO

SELECT SUBSTRING(CONVERT(NVARCHAR(50), NEWID()),0,9)

SELECT DATEADD(DAY, (ABS(CHECKSUM(NEWID())) % 5475), '2000-01-01')
